import { spawn } from 'node:child_process';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
const dir = new URL('.', import.meta.url).pathname;
const vistaTest = dir + 'vista-test.json';
writeFileSync(vistaTest, JSON.stringify({ generatoIl: new Date().toISOString(), studioNome: 'T', annoCorrente: 2026, clienti: [], scadenze: [], task: [], adempimentiAnnuali: [] }));
const p = spawn('node', [dir + 'server-http.js'], { env: { ...process.env, PRISMA_MCP_HTTP_PORT: '18421', GESTIONALE_MCP_FILE: vistaTest }, stdio: 'ignore' });
await new Promise(r => setTimeout(r, 40000));
const token = readFileSync(dir + 'token-ia.txt', 'utf8').trim();
const H = { 'Content-Type': 'application/json', Accept: 'application/json, text/event-stream' };
let ko = 0; const t = (n, c) => { console.log((c ? 'OK  ' : 'KO  ') + n); if (!c) ko++; };
let r = await fetch('http://127.0.0.1:18421/mcp', { method: 'POST', headers: H, body: '{}' }); t('senza token = 401', r.status === 401);
r = await fetch('http://127.0.0.1:18421/mcp/sbagliato', { method: 'POST', headers: H, body: '{}' }); t('token errato = 401', r.status === 401);
const init = { jsonrpc: '2.0', id: 1, method: 'initialize', params: { protocolVersion: '2025-03-26', capabilities: {}, clientInfo: { name: 't', version: '1' } } };
r = await fetch('http://127.0.0.1:18421/mcp', { method: 'POST', headers: { ...H, Authorization: 'Bearer ' + token }, body: JSON.stringify(init) }); t('bearer initialize 200', r.status === 200);
r = await fetch('http://127.0.0.1:18421/mcp/' + token, { method: 'POST', headers: H, body: JSON.stringify({ jsonrpc: '2.0', id: 2, method: 'tools/list', params: {} }) });
const j = await r.json(); t('token nell\'URL: tools/list > 40 tool (' + (j.result && j.result.tools.length) + ')', j.result && j.result.tools.length > 40);
r = await fetch('http://127.0.0.1:18421/mcp/' + token, { method: 'POST', headers: H, body: JSON.stringify({ jsonrpc: '2.0', id: 3, method: 'tools/call', params: { name: 'stato_generale', arguments: {} } }) });
const k = await r.json(); t('stato_generale risponde', k.result && /clientiAttivi/.test(JSON.stringify(k.result)));
p.kill(); console.log(ko ? 'FALLITI ' + ko : 'TUTTO OK'); process.exit(ko ? 1 : 0);
